//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Infraestructura.AccesoDatos.Repositorio
{
    using Inmobiliaria.Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INMOBILIARIAEntities1 : DbContext
    {
        public INMOBILIARIAEntities1()
            : base("name=INMOBILIARIAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BARRIO> BARRIO { get; set; }
        public virtual DbSet<CANTON> CANTON { get; set; }
        public virtual DbSet<CARACTERISTICA> CARACTERISTICA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<IMAGEN> IMAGEN { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<PARROQUIA> PARROQUIA { get; set; }
        public virtual DbSet<PROPIEDAD> PROPIEDAD { get; set; }
        public virtual DbSet<PROPIETARIO> PROPIETARIO { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPO_PROPIEDAD> TIPO_PROPIEDAD { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
