//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARRIO
    {
        public int IDBARRIO { get; set; }
        public Nullable<int> IDPARROQUIA { get; set; }
        public string BARRIO1 { get; set; }
        public int ESTADOBARRIO { get; set; }
    
        public virtual PARROQUIA PARROQUIA { get; set; }
    }
}
