//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANTON()
        {
            this.PARROQUIA = new HashSet<PARROQUIA>();
        }
    
        public int IDCANTON { get; set; }
        public Nullable<int> IDPROVINCIA { get; set; }
        public string CODCANTON { get; set; }
        public string NOMBRECANTON { get; set; }
        public int ESTADOCANTON { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARROQUIA> PARROQUIA { get; set; }
    }
}
