//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN
    {
        public int IDIMAGEN { get; set; }
        public Nullable<int> IDPROPIEDAD { get; set; }
        public string PATH { get; set; }
        public int ESTADOIMAGEN { get; set; }
    
        public virtual PROPIEDAD PROPIEDAD { get; set; }
    }
}
