//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARROQUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARROQUIA()
        {
            this.BARRIO = new HashSet<BARRIO>();
        }
    
        public int IDPARROQUIA { get; set; }
        public Nullable<int> IDCANTON { get; set; }
        public string NOMBREPARROQUIA { get; set; }
        public int ESTADOPARROQUIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BARRIO> BARRIO { get; set; }
        public virtual CANTON CANTON { get; set; }
    }
}
