//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIETARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPIETARIO()
        {
            this.PROPIEDAD = new HashSet<PROPIEDAD>();
        }
    
        public int IDPROPIETARIO { get; set; }
        public string NOMBREPROPIETARIO { get; set; }
        public string DIRECCIONPROPIETARIO { get; set; }
        public string CELULARPROPIETARIO { get; set; }
        public string CORRREOPROPIETARIO { get; set; }
        public int ESTADOPROPIETARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPIEDAD> PROPIEDAD { get; set; }
    }
}
