//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPIEDAD()
        {
            this.IMAGEN = new HashSet<IMAGEN>();
        }
    
        public int IDPROPIEDAD { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDCARACTERISTICA { get; set; }
        public Nullable<int> IDPROVINCIA { get; set; }
        public Nullable<int> IDTIPOPROPIEDAD { get; set; }
        public Nullable<int> IDPROPIETARIO { get; set; }
        public decimal PRECIO { get; set; }
        public int ESTADOPROPIEDAD { get; set; }
    
        public virtual CARACTERISTICA CARACTERISTICA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN> IMAGEN { get; set; }
        public virtual PROPIETARIO PROPIETARIO { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual TIPO_PROPIEDAD TIPO_PROPIEDAD { get; set; }
    }
}
